name: "llava-hf/llava-1.5-7b-hf"
class_name: VQAModel
pt: null
inner_params: ["model.language_model.layers.31.mlp.gate_proj.weight"] # conventional layer
inner_params_vision: ["model.language_model.layers.27.mlp.gate_proj.weight"]
inner_params_lang: ["model.language_model.layers.31.mlp.gate_proj.weight"]
processor_class: null
tokenizer_class: null
temperature: 0.0
