name: "Qwen/Qwen3-VL-4B-Instruct"
class_name: VQAModel
pt: null
inner_params: ["model.language_model.layers.35.mlp.gate_proj.weight"] # conventional layer
inner_params_vision: ["model.visual.blocks.21.mlp.linear_fc1.weight"] # vision layer
inner_params_lang: ["model.language_model.layers.22.mlp.gate_proj.weight"] # langauge layer
lang_scaler_sbert: 42 #30
cap_keys: 7
processor_class: null
tokenizer_class: null
temperature: 0.0

