_name: grace
edit_lr: 1e-2
n_iter: 500
eps: 0.1
dist_fn: cos  # Options: euc, cos, mmd
replacement: replace_all  # Options: replace_all, replace_last
early_stop_patience: 50  # Stop training if loss doesn't decrease for N iterations

