# @package _global_
hydra:
  sweeper:
    params:
      +run_name: "locality_run" 
      +log_filename: "locality_run" # log file name

      # paths
      +repo_root: /home/sgw3fy/jobs/model_editing_jobs/repos/instruct_vlm_edit
      +loc_sample_path: /home/sgw3fy/jobs/model_editing_jobs/repos/instruct_vlm_edit/aux_files/locality_eval/wrong_3_edits_same_qa.pkl

      # editing parameters
      +editor_name: ike_chain
      +model_name: qwen3_4b
      +dataset_name: aokvqa
      +task: mc
      +q_index: 0, 1, 2, 3, 4 # 0, 1, 2, 3, 4, 5, 6, 7

      # general parameters
      +namespace_config_path: "/home/sgw3fy/jobs/model_editing_jobs/repos/instruct_vlm_edit/revlm/config/config.yaml"