# @package _global_
hydra:
  sweeper:
    params:
      +current_step: "ltr" 
      +log_filename: "alteration_truncation" # log file name

      # paths
      +repo_root: /home/sgw3fy/jobs/model_editing_jobs/repos/instruct_vlm_edit
      +biases_path: /home/sgw3fy/jobs/model_editing_jobs/repos/instruct_vlm_edit/aux_files/subsample_edits/aokvqa-tr-alt_cot-01.json, /home/sgw3fy/jobs/model_editing_jobs/repos/instruct_vlm_edit/aux_files/subsample_edits/aokvqa-tr-alt_cot-05.json, /home/sgw3fy/jobs/model_editing_jobs/repos/instruct_vlm_edit/aux_files/subsample_edits/aokvqa-tr-alt_cot-025.json, /home/sgw3fy/jobs/model_editing_jobs/repos/instruct_vlm_edit/aux_files/subsample_edits/aokvqa-tr-alt_cot2-01.json, /home/sgw3fy/jobs/model_editing_jobs/repos/instruct_vlm_edit/aux_files/subsample_edits/aokvqa-tr-alt_cot2-05.json, /home/sgw3fy/jobs/model_editing_jobs/repos/instruct_vlm_edit/aux_files/subsample_edits/aokvqa-tr-cot2-025.json
      +subsample_path: /home/sgw3fy/jobs/model_editing_jobs/repos/instruct_vlm_edit/aux_files/subsample_edits/aokvqa.json

      # editing parameters
      +editor_name: ike_chain
      +model_name: qwen3_4b
      +dataset_name: aokvqa
      +task: mc
      +subsample: 0
      +subsample_edits: 500

      # general parameters
      +namespace_config_path: "/home/sgw3fy/jobs/model_editing_jobs/repos/instruct_vlm_edit/revlm/config/config.yaml"